stages:
  - maven
  - android

maven-package:
  image: maven:3.5-jdk-8
  tags:
    - docker
  stage: maven
  script:
    - echo ${docker_password} | docker login registry.cn-beijing.aliyuncs.com -u ${docker_username} --password-stdin
#    - docker login registry.cn-beijing.aliyuncs.com -u roma@guanweiming.com -p gwm302735803
#    - docker build -t registry.cn-beijing.aliyuncs.com/guanweiming/maven:3.8.1-openjdk-11 ./maven/jdk11
#    - docker push registry.cn-beijing.aliyuncs.com/guanweiming/maven:3.8.1-openjdk-11
#    - docker build -t registry.cn-beijing.aliyuncs.com/guanweiming/maven:3.5-jdk-8 ./maven/jdk8
#    - docker push registry.cn-beijing.aliyuncs.com/guanweiming/maven:3.5-jdk-8


android-package:
  image: registry.cn-beijing.aliyuncs.com/guanweiming/maven:3.5-jdk-8
  tags:
    - docker
  stage: android
  script:
    - echo ${docker_password} | docker login registry.cn-beijing.aliyuncs.com -u ${docker_username} --password-stdin
#    - docker build -t registry.cn-beijing.aliyuncs.com/guanweiming/android:31.0.0 ./android/31.0.0
#    - docker push registry.cn-beijing.aliyuncs.com/guanweiming/android:31.0.0
#    - docker build -t registry.cn-beijing.aliyuncs.com/guanweiming/android:30.0.3 ./android/30.0.3
#    - docker push registry.cn-beijing.aliyuncs.com/guanweiming/android:30.0.3
    - docker build -t registry.cn-beijing.aliyuncs.com/guanweiming/android:29.0.3 ./android/29.0.3
    - docker push registry.cn-beijing.aliyuncs.com/guanweiming/android:29.0.3
#    - docker build -t registry.cn-beijing.aliyuncs.com/guanweiming/android:28.0.3 ./android/28.0.3
#    - docker push registry.cn-beijing.aliyuncs.com/guanweiming/android:28.0.3
#    - docker build -t registry.cn-beijing.aliyuncs.com/guanweiming/android:28.0.2 ./android/28.0.2
#    - docker push registry.cn-beijing.aliyuncs.com/guanweiming/android:28.0.2





