stages:
  - gitbook
  - maven
  - package

maven-package:
  image: maven:3.5-jdk-8
  tags:
    - pre
  stage: maven
  script:
    - echo ${docker_password} | docker login registry.cn-zhangjiakou.aliyuncs.com -u ${docker_username} --password-stdin
#    - docker build -t registry.cn-zhangjiakou.aliyuncs.com/guanweiming/maven:3.8.3-openjdk-8 maven/jdk8
#    - docker push registry.cn-zhangjiakou.aliyuncs.com/guanweiming/maven:3.8.3-openjdk-8
#    - docker build -t registry.cn-zhangjiakou.aliyuncs.com/guanweiming/maven:3.8.3-openjdk-8-pre maven/jdk8-pre
#    - docker push registry.cn-zhangjiakou.aliyuncs.com/guanweiming/maven:3.8.3-openjdk-8-pre
#    - docker build -t registry.cn-zhangjiakou.aliyuncs.com/guanweiming/maven:3.8.3-openjdk-8-prod maven/jdk8-prod
#    - docker push registry.cn-zhangjiakou.aliyuncs.com/guanweiming/maven:3.8.3-openjdk-8-prod
#    - docker build -t registry.cn-zhangjiakou.aliyuncs.com/guanweiming/openjdk:8u312-jre java/openjdk/8
#    - docker push registry.cn-zhangjiakou.aliyuncs.com/guanweiming/openjdk:8u312-jre
#    - docker build -t registry.cn-zhangjiakou.aliyuncs.com/guanweiming/openjdk:11.0.13-jre java/openjdk/11
#    - docker push registry.cn-zhangjiakou.aliyuncs.com/guanweiming/openjdk:11.0.13-jre
#    - docker build -t registry.cn-zhangjiakou.aliyuncs.com/guanweiming/maven:3.8.4-jdk-11 maven/jdk11
#    - docker push registry.cn-zhangjiakou.aliyuncs.com/guanweiming/maven:3.8.4-jdk-11



android-package:
  image: registry.cn-zhangjiakou.aliyuncs.com/guanweiming/maven:3.8.3-openjdk-8
  tags:
    - pre
  stage: package
  script:
    - echo ${docker_password} | docker login registry.cn-beijing.aliyuncs.com -u ${docker_username} --password-stdin
    - ls /root/.m2
#    - docker build -t registry.cn-beijing.aliyuncs.com/guanweiming/android:29.0.2 ./android/29.0.2
#    - docker push registry.cn-beijing.aliyuncs.com/guanweiming/android:29.0.2
#    - docker build -t registry.cn-beijing.aliyuncs.com/guanweiming/android:31.0.0 ./android/31.0.0
#    - docker push registry.cn-beijing.aliyuncs.com/guanweiming/android:31.0.0
#    - docker build -t registry.cn-beijing.aliyuncs.com/guanweiming/android:30.0.3 ./android/30.0.3
#    - docker push registry.cn-beijing.aliyuncs.com/guanweiming/android:30.0.3
#    - docker build -t registry.cn-beijing.aliyuncs.com/guanweiming/android:29.0.3 ./android/29.0.3
#    - docker push registry.cn-beijing.aliyuncs.com/guanweiming/android:29.0.3
#    - docker build -t registry.cn-beijing.aliyuncs.com/guanweiming/android:28.0.3 ./android/28.0.3
#    - docker push registry.cn-beijing.aliyuncs.com/guanweiming/android:28.0.3
#    - docker build -t registry.cn-beijing.aliyuncs.com/guanweiming/android:28.0.2 ./android/28.0.2
#    - docker push registry.cn-beijing.aliyuncs.com/guanweiming/android:28.0.2



runner-package:
  image: registry.cn-zhangjiakou.aliyuncs.com/guanweiming/maven:3.8.3-openjdk-8
  tags:
    - pre
  stage: package
  script:
    - echo ${docker_password} | docker login registry.cn-zhangjiakou.aliyuncs.com -u ${docker_username} --password-stdin
#    - docker pull bitnami/kubectl:latest
#    - docker tag bitnami/kubectl:latest registry.cn-zhangjiakou.aliyuncs.com/guanweiming/kubectl:latest
#    - docker push registry.cn-zhangjiakou.aliyuncs.com/guanweiming/kubectl:latest
#    - docker build -t registry.cn-beijing.aliyuncs.com/guanweiming/gitlab-runner:v14.2.0 ./gitlab-runner/v14.2.0
#    - docker push registry.cn-beijing.aliyuncs.com/guanweiming/gitlab-runner:v14.2.0
    - docker build -t registry.cn-beijing.aliyuncs.com/guanweiming/gitlab-runner:v14.7.0 ./gitlab-runner/v14.7.0
    - docker push registry.cn-beijing.aliyuncs.com/guanweiming/gitlab-runner:v14.7.0
#    - docker build -t registry.cn-beijing.aliyuncs.com/guanweiming/gitlab-runner:v14.2.0 ./gitlab-runner/v14.2.0
#    - docker push registry.cn-beijing.aliyuncs.com/guanweiming/gitlab-runner:v14.2.0

runner-gitbook:
  image: registry.cn-zhangjiakou.aliyuncs.com/guanweiming/maven:3.8.3-openjdk-8
  tags:
    - pre
  stage: gitbook
  script:
    - echo ${docker_password} | docker login registry.cn-zhangjiakou.aliyuncs.com -u ${docker_username} --password-stdin
#    - docker build -t registry.cn-zhangjiakou.aliyuncs.com/guanweiming/gitbook-pdf:v1.9 ./gitbook/pdf
#    - docker push registry.cn-zhangjiakou.aliyuncs.com/guanweiming/gitbook-pdf:v1.9
#    - docker pull bitnami/kubectl:latest
#    - docker tag bitnami/kubectl:latest registry.cn-zhangjiakou.aliyuncs.com/guanweiming/kubectl:latest
#    - docker push registry.cn-zhangjiakou.aliyuncs.com/guanweiming/kubectl:latest
#    - docker build -t registry.cn-beijing.aliyuncs.com/guanweiming/gitlab-runner:v14.2.0 ./gitlab-runner/v14.2.0
#    - docker push registry.cn-beijing.aliyuncs.com/guanweiming/gitlab-runner:v14.2.0
    - docker build -t registry.cn-zhangjiakou.aliyuncs.com/guanweiming/gitlab-runner:v14.7.0 ./gitlab-runner/v14.7.0
    - docker push registry.cn-zhangjiakou.aliyuncs.com/guanweiming/gitlab-runner:v14.7.0
