stages:
  - build

maven-package:
  image: registry.cn-zhangjiakou.aliyuncs.com/tulan/maven:openjdk-11
  tags:
    - dev
  stage: build
  script:
    - echo ${docker_password} | docker login registry.cn-zhangjiakou.aliyuncs.com -u ${tulan_username} --password-stdin
#    - docker build -t registry.cn-zhangjiakou.aliyuncs.com/guanweiming/openjdk:11-speex java/openjdk/11-speex
#    - docker push registry.cn-zhangjiakou.aliyuncs.com/guanweiming/openjdk:11-speex
#    - docker build -t registry.cn-zhangjiakou.aliyuncs.com/tulan/node:16 ./npm/node/16
#    - docker push registry.cn-zhangjiakou.aliyuncs.com/tulan/node:16
    - ./build.sh node:14 npm/node/14
