name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: 登陆docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: |
          echo "构建"
          export docker_hub_username=${{ secrets.DOCKER_USERNAME }}
          ./build.sh gitlab-runner:v15.8.0      gitlab-runner/v15.8.0
          ./build.sh openjdk:11                 java/openjdk/11
          ./build.sh openjdk:11.0.16-jre        java/openjdk/11
          ./build.sh openjdk:11.0.16-jre-ffmpeg java/openjdk/11-ffmpeg
          ./build.sh openjdk:8                  java/openjdk/8
          ./build.sh openjdk:8u342-jre          java/openjdk/8
          ./build.sh openjdk:8u342-jre-ffmpeg   java/openjdk/8-ffmpeg
          ./build.sh maven:3.8.6-openjdk-8      maven/jdk8
          ./build.sh maven:jdk8                 maven/jdk8
          ./build.sh maven:3.8.6-openjdk-11     maven/jdk11
          ./build.sh maven:jdk11                maven/jdk11
          ./build.sh gitbook:3.2.3              gitbook
          ./build.sh node:14                    npm/node/14
          ./build.sh node:16                    npm/node/16
          ./build.sh nginx-proxy-manager:2.9.19 nginx
          ./build.sh android:30.0.3             android/30.0.3
#          docker build -t guangee/nacos:1.4.2 nacos/1.4.2/
#          docker push guangee/nacos:1.4.2
#          docker build -t guangee/gitbook:3.2.3 gitbook/3.2.3/
#          docker push guangee/gitbook:3.2.3
#          docker build -t guangee/nacos:1.4.0 nacos/1.4.0/
#          docker push guangee/nacos:1.4.0

